spring:
  application:
    name: authentication
  datasource:
    url: jdbc:mysql://localhost:3306/fit_finance?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081
  servlet:
    context-path: /

logging:
  level:
    root: info
    org:
      hibernate:
        SQL: INFO