#spring.application.name=Fit-Finance
#spring.datasource.url=jdbc:mysql://localhost:3306/fit_finance?createDatabaseIfNotExist=true
server:
  port: 8080
  error:
    include-stacktrace: on_param
  tomcat:
    relaxed-query-chars: '|,{,},[,]'
  servlet:
    context-path: /

spring:
  application:
    name: fit-finance-backend
  datasource:
    url: jdbc:mysql://localhost:3306/fit_finance?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org:
      hibernate:
        SQL: INFO

management:
  server:
    port: 8989
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days